
development:
  adapter: postgresql
  encoding: unicode
  database: me2meDos_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: me2meDos_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: me2meDos_prod
  pool: 25
